import { siteConfig } from "@/config/site";

export const allCategories = [
  {
    name: "Name Generate",
    href: siteConfig.routes.nameGenerate,
    description: "Generate random names",
    isActive: true,
    isDemo: false,
    cover: "/imgs/name_generate_cover.png",
  },
  {
    name: "Password Generate",
    href: siteConfig.routes.passwordGenerate,
    description: "Create secure passwords",
    isActive: true,
    isDemo: false,
    cover: "/imgs/password_generate_cover.png",
  },
  {
    name: "DOB Generate",
    href: siteConfig.routes.dobGenerate,
    description: "Generate random dates of birth",
    isActive: true,
    isDemo: false,
    cover: "/imgs/dob_generate_cover.png",
  },
  {
    name: "Passport Generate",
    href: siteConfig.routes.passportGenerate,
    description: "Generate passport id numbers",
    isActive: false,
    isDemo: false,
    cover: "/imgs/passport_generate_cover.png",
  },
  {
    name: "Passport Expire Generate",
    href: siteConfig.routes.passportExpireGenerate,
    description: "Generate passport expiration dates",
    isActive: false,
    isDemo: false,
    cover: "/imgs/passport_expire_generate_cover.png",
  },
  {
    name: "Iban Generate",
    href: siteConfig.routes.ibanGenerate,
    description: "Generate IBAN numbers",
    isActive: false,
    isDemo: false,
    cover: "/imgs/iban_generate_cover.png",
  },
  {
    name: "Location Generate",
    href: siteConfig.routes.locationGenerate,
    description: "Generate random locations",
    isActive: false,
    isDemo: true,
    cover: "/imgs/locations_generate_cover.png",
  },
];
